[project]
name = "bolletta-storage-agent"
version = "0.1.0"
description = ""
authors = [
    { name = "Gab25", email = "gabrielesorci.25@gmail.com" },
]
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.13"
dependencies = [
    "google-adk (>=0.2.0,<0.3.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
